name: puby
description: Dart-based CLI app for managing dependencies in pubspec.yaml
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.19.0-444.3.beta"

dependencies:
  # CLI arguments parser
  args: ^2.3.1

  # YAML
  yaml: ^3.1.1

  # Utilities
  dart_scope_functions: ^0.0.2
  ktuples: ^0.0.2
  collection: ^1.17.0
  meta: ^1.8.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
