name: puby
description: Dart-based CLI app for managing dependencies in pubspec.yaml
version: 2.0.0
publish_to: "none"

environment:
  sdk: ">=3.1.5"

dependencies:
  # CLI arguments parser
  args: ^2.4.2

  # YAML
  yaml: ^3.1.2

  # Utilities
  dart_scope_functions: ^0.1.4
  collection: ^1.18.0
  meta: ^1.11.0
  equatable: ^2.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
